### ISSUE TITLE
How to login to Terramate using GitHub actions

### ISSUE THREAD

**Issue by bart-braidwell** [terramate-io/terramate-quickstart-aws#175]
Hello,

Looking for a way to authenticate github actions with terramate cloud.
When using CI/CD pipeline for preview (https://terramate.io/docs/cli/automation/github-actions/preview-workflow)
I got an issue that says I am not logged in. Cant find a proper configuration on how to do that in github actions. 
Can I add github token somewhere in terramate ?
![image](https://github.com/terramate-io/terramate-quickstart-aws/assets/115633466/b8069316-fb59-4f99-ace4-fca1203701a5)

**Comment by bart-braidwell** [comment]
solved it - you need to add GitHub trust in your terramate organization setup in cloud.
The value for GitHub trust should be your organization/repo name

for example. "terramate-io/infrastructure_repo"

https://terramate.io/docs/cloud/organization/settings

**Comment by soerenmartius** [comment]
> solved it - you need to add GitHub trust in your terramate organization setup in cloud. The value for GitHub trust should be your organization/repo name
> 
> for example. "terramate-io/infrastructure_repo"
> 
> https://terramate.io/docs/cloud/organization/settings

That's correct @bart-braidwell

We need to make the docs a lot more clear. I'll am currently putting a lot of time into more actionable docs and guides (including the README for this repo). I'd love to learn more about your use case for Terramate, perhaps we can jump on a call together?
